#!/usr/bin/env node
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
// No argument: sync the root-level plugin manifests — the repository root IS the
// plugin (superpowers-style). With an argument: build a portable bundle
// (full skill set) to that directory.
const output = process.argv[2] ? resolve(process.argv[2]) : null;
const packageJson = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const repository = packageJson.repository.url.replace(/^git\+/, '');
const commandSlugs = readdirSync(join(root, 'commands'))
  .filter(f => f.endsWith('.md'))
  .map(f => f.replace(/\.md$/, ''))
  .sort();

function writeJson(target, value) {
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, `${JSON.stringify(value, null, 2)}\n`);
}

function copy(relativeSource, relativeTarget = relativeSource) {
  const source = join(root, relativeSource);
  if (!existsSync(source)) throw new Error(`Missing source: ${relativeSource}`);
  cpSync(source, join(output, relativeTarget), { recursive: true });
}

const coreManifest = {
  '$schema': 'https://agent-plugins.org/schemas/1.0.0/plugin.schema.json',
  name: 'wagents',
  version: packageJson.version,
  description: packageJson.description,
  author: { name: 'wagents maintainers' },
  homepage: packageJson.homepage,
  repository,
  license: 'MIT',
  keywords: [...new Set([...packageJson.keywords, ...commandSlugs])],
  commands: commandSlugs.length
    ? commandSlugs.map(slug => ({ name: `/wagents:${slug}`, file: `commands/${slug}.md` }))
    : undefined
};

function claudePluginJson() {
  return {
    name: 'wagents',
    version: packageJson.version,
    description: packageJson.description,
    author: { name: 'wagents maintainers' },
    homepage: packageJson.homepage,
    repository,
    license: 'MIT'
  };
}

function codexPluginJson() {
  return {
    name: 'wagents',
    version: packageJson.version,
    description: packageJson.description,
    author: { name: 'wagents maintainers' },
    homepage: packageJson.homepage,
    repository,
    license: 'MIT',
    skills: './skills/'
  };
}

// MCPs need user-specific credentials, OAuth consent, and per-agent selection.
// Keep the portable core deliberately empty and generate client configuration from mcp/servers.json.
function emptyMcpJson() {
  return {
    '$schema': 'https://agent-plugins.org/schemas/1.0.0/mcp.schema.json',
    mcpServers: {}
  };
}

function syncRootManifests() {
  writeJson(join(root, 'plugin.json'), coreManifest);
  writeJson(join(root, '.claude-plugin', 'plugin.json'), claudePluginJson());
  writeJson(join(root, '.codex-plugin', 'plugin.json'), codexPluginJson());
  writeJson(join(root, 'mcp.json'), emptyMcpJson());
  console.log('[wagents] synced plugin manifests at the repository root (repo root is the plugin)');
}

function buildBundle() {
  rmSync(output, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 });
  mkdirSync(output, { recursive: true });
  copy('skills');
  copy('agents');
  copy('instructions');
  copy('LICENSE');
  // Per-skill licenses and provenance are retained by the recursive skills copy.
  // Full skill set ships everywhere (personal-use repository).

  // Slash-command documentation and lifecycle hooks are portable and live under the plugin root.
  // hooks.json references ${CLAUDE_PLUGIN_ROOT}/hooks/run-hook.cmd, so the whole hooks/ tree is packaged.
  copy('commands', 'commands');
  copy('hooks', 'hooks');
  writeJson(join(output, 'plugin.json'), coreManifest);
  writeJson(join(output, '.claude-plugin', 'plugin.json'), claudePluginJson());
  writeJson(join(output, '.codex-plugin', 'plugin.json'), codexPluginJson());
  writeJson(join(output, 'mcp.json'), emptyMcpJson());
  writeFileSync(join(output, 'README.md'), `# wagents plugin\n\nPortable bundle generated by \`node scripts/build-plugin.mjs <dir>\`.\n\nThe full skill set, agent roles, slash-command documentation, and lifecycle hooks are portable.\nSlash commands are documented under \`commands/\`; lifecycle hooks are under \`hooks/\`.\n\nMCP connections are intentionally not bundled: they can require OAuth, local vault access, paid licenses, or privileged credentials. Use the repository [MCP setup guide](../../mcp/README.md).\n`);
  console.log(`[wagents] built portable bundle at ${output}`);
}

if (output) {
  buildBundle();
} else {
  syncRootManifests();
}
